spring:
  application:
    name: payment-service

  mongodb:
    uri: mongodb://localhost:27017/payments_db

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  random-api:
    url: "https://www.random.org"

server:
  port: 8083